#!/bin/ash
#copyright by monlor
source /etc/monlor/scripts/base.sh
param=$1
Applist=$monlorpath/config/applist.txt

manage() {

	clear
	echo "********************************"
	echo "  **** Monlor Tools工具箱 ****"
	echo "********************************"
	echo
	echo "0. 返回主菜单"
	echo "1. 更新工具箱"
	echo "2. 卸载工具箱"
	echo "3. 卸载插件"
	read -p "请输入你的选择：" select
	case "$select" in
		0)
			menu
		;;
		1)
			update.sh
		;;
		2)
			uninstall.sh
		;;
		3)
			read -p "请输入要卸载的插件名：" name
			if [ `cat $Applist | grep -wc $name` -eq 1 ]; then
				appmanage.sh del $name
			else 
				echo "输入有误！"
			fi
		;;
	esac
			


}

menu() {

	i=0;
	clear
	echo "********************************"
	echo "  **** Monlor Tools工具箱 ****"
	echo "********************************"
	echo "`check_version`"
	echo 
	echo "0. 工具箱/插件管理(Ctrl + c退出)"
	cat $Applist | while read line
	do
		let i=$i+1
		echo "$i. $line`check_install $line`"
	done
	read -p "请输入你的选择：" select
	if [ `echo $select | grep -c '^[0-9][0-9]*$'` -eq 1 ]; then
		if [ "$select" == '0' ]; then
			manage
		elif [ "$select" -gt '0' ] && [ "$select" -le "$(cat $Applist | wc -l)" ]; then
			appname=$(cat $Applist | grep -n . | grep -w $select | cut -d: -f2)
			if [ `checkuci $appname` == '0' ]; then
				$appname
			else
				read -p "确定要安装$appname插件？[1/0]" install
				[ "$install" = '1' ] && appmanage.sh add $appname || menu
			fi
		else 
			echo "输入有误！"
			exit
		fi
	else
		echo "输入有误！"
	fi


}

check_install() {

	if [ `checkuci $1` == '0' ]; then
		status=$($monlorpath/apps/$1/script/$1.sh status | head -1)
		echo -n "[$status]"
	else 
		echo -n "[选择以安装]"
	fi
}

check_version() {

	newver=$(cat /tmp/tools_version.txt) > /dev/null 2>&1
	oldver=$(cat $monlorpath/config/version.txt)
	echo -n "当前版本：$oldver 最新版本：$newver"

}

if [ ! -z $param ]; then $param; else menu; fi #monlor-if
