#!/bin/ash
#copyright by monlor
source /etc/monlor/scripts/base.sh
param=$1
Applist=$monlorpath/config/applist.txt

manage() {

	clear
	echo "************************************"
	echo "   ***** Monlor Tools工具箱 *****"
	echo "************************************"
	echo
	echo "0. 返回主菜单"
	echo "1. 更新工具箱"
	echo "2. 卸载工具箱"
	echo "3. 卸载插件"
	xunlei=$(uci -q get monlor.tools.xunlei)
	[ "$xunlei" == '1' ] && xunlei="已关闭" || xunlei="未关闭"
	echo "4. 关闭迅雷($xunlei)"
	samba_path=$(uci -q get monlor.tools.samba_path)
	[ ! -z "$samba_path" ] && samba_path="$samba_path" || samba_path="未修改"
	echo "5. 修改samba路径（$samba_path）"
	echo
	read -p "请输入你的选择：" select
	case "$select" in
		0)
			menu
		;;
		1)
			update.sh
		;;
		2)
			uninstall.sh && exit
		;;
		3)
			echo "0.返回"
			cat $Applist | grep -n .
			read -p "请选择要卸载的插件：" res
			if [ "$res" == '0' ]; then
				manage
			else
				appname=$(cat $Applist | grep -n . | grep -w $res | cut -d: -f2)
				[ ! -z "$appname" ] && appmanage.sh del $appname
			fi
		;;
		4)
			read -p "确定要关闭迅雷服务？[1/0] " xunlei
			[ `checkread $xunlei` ] && uci set monlor.tools.xunlei="$xunlei"
			if [ "$xunlei" == '1' ]; then
				mv /usr/sbin/xunlei.sh /usr/sbin/xunlei.sh.bak > /dev/null 2>&1
				killall xunlei > /dev/null 2>&1
				killall etm > /dev/null 2>&1
			fi
		;;
		5)
			read -p "请输入新的samba路径：" samba_path
			[ ! -d "$samba_path" -a ! -z "$samba_path" ] && mkdir -p $samba_path
			uci set monlor.tools.samba_path="$samba_path"
		
		;;
		*)	
			echo "输入有误！"
			manage
		;;
	esac

}

menu() {

	i=0;
	clear
	echo "********************************"
	echo "  **** Monlor Tools工具箱 ****"
	echo "********************************"
	echo "`check_version`"
	echo 
	echo "0. 工具箱/插件管理(Ctrl + c退出)"
	cat $Applist | while read line
	do
		let i=$i+1
		echo "$i. $line`check_install $line``check_update $line`"
	done
	echo
	read -p "请输入你的选择：" select
	echo
	[ "$select" == "exit" ] && exit
	if [ `echo $select | grep -c '^[0-9][0-9]*$'` -eq 1 ]; then
		if [ "$select" == '0' ]; then
			manage
		elif [ "$select" -gt '0' ] && [ "$select" -le "$(cat $Applist | wc -l)" ]; then
			appname=$(cat $Applist | grep -n . | grep -w $select | cut -d: -f2)
			if [ `checkuci $appname` == '0' ]; then
				if [ ! -z `check_update $appname` ]; then
					read -p "是否要更新$appname插件？[1/0] " update
					[ "$update" == '1' ] && appmanage.sh upgrade $appname || $appname
				else
					$appname
				fi
			else
				read -p "确定要安装$appname插件？[1/0] " install
				[ "$install" = '1' ] && appmanage.sh add $appname 
			fi
		else 
			echo "输入有误！"
			exit
		fi
	else
		echo "输入有误！"
	fi
	uci commit monlor
	read -p "返回主菜单？[1/0] " res
	if [ `checkread $res` ]; then
		[ "$res" == '1' ] && menu || exit
	fi

}

check_install() {

	if [ `checkuci $1` == '0' ]; then
		status=$($monlorpath/apps/$1/script/$1.sh status | head -1) > /dev/null 2>&1
		echo -n "[$status]"
	else 
		echo -n "[选择以安装]"
	fi
}

check_update() {

	newver=$(cat /tmp/version/$1.txt) > /dev/null 2>&1
	oldver=$(cat $monlorpath/apps/$1/config/version.txt) > /dev/null 2>&1
	if [ ! -z "$newver" -a ! -z "$oldver" ] && [ "$newver" != "$oldver" ]; then
		echo -n "[有更新]"
	fi

}

check_version() {

	newver=$(cat /tmp/tools_version.txt) > /dev/null 2>&1
	oldver=$(cat $monlorpath/config/version.txt)
	echo -n "当前版本：$oldver 最新版本：$newver"

}

if [ ! -z $param ]; then $param; else menu; fi; #monlor-if
